export default {
  config: {
    locale: 'GB',
    groupBookingUrl: '/gb/en/why/groups.html',
    hotelBrands: {
      hub: 'hub',
      pi: 'pi',
      zip: 'zip',
    },
    roomCodes: {
      family: 'FAM',
      single: 'SB',
      double: 'DB',
      accessible: 'DIS',
      twin: 'TWIN',
    },
    api: {
      initialPageSize: 40,
      lazyLoadPageSize: 10,
      connectivity: true,
      imagesUrl: 'https://www.premierinn.com',
      availabilities: {
        domain: 'https://api-uat.whitbread.co.uk',
        method: '/search/hotels',
        hotels: '/hotels',
        datelessUrl: '/search/hotels',
      },
      availability: {
        domain: 'https://api-uat.whitbread.co.uk',
        preMethod: '/booking/hotels',
        postMethod: '/availability',
      },
      snowdrop: {
        autocomplete: {
          enabled: false,
          domain: 'https://api-uat.whitbread.co.uk',
          method: '/autocomplete?input=',
          defaultResponseLength: 5,
          managedPlacesSize: 1,
          googlePlacesSize: 4,
          googlePlaces: 'gplaces[components]=',
          countryRestrictions: [
            { countries: 'uk' },
          ],
        },
        availabilities: {
          enabled: false,
          domain: 'https://api-uat.whitbread.co.uk',
          datelessUrl: '/snowdrop/search/hotels',
          method: '/snowdrop/search/hotels/availabilities',
        },
      },
      beaconDodsworth: {
        domain: 'https://www.premierinn.com',
        method: '/services/en/mobileHotelLocator/suggestions',
        basicAuth: 'what:whit',
      },
      reservations: {
        domain: 'https://api-uat-alpha1.whitbread.co.uk',
        method: '/reservation/hotels',
        incorrectCBTBookingChannelExceptionCode: '2001',
      },
    },
    hotelDetails: {
      hotelPath: '/gb/en/hotels',
      hotelDirectoryPath: '/gb/en/hoteldirectory',
      domain: {
        desktop: '//www.',
      },
    },
    authentication: {
      businessLoginEnabled: true,
      businessLegacyLoginEnabled: false,
      businessLegacyLoginEndpoint: 'https://bb-develop.ode.whitbread.digital/login',
      leisureForgottenPasswordEnabled: true,
      businessForgottenPasswordEnabled: true,
      timeSwitchingTab: true,
      iframePath: 'https://secure2-ode-mypi.ode.dev.premierinn.digital/gb/en/common/login.html',
      leisure: {
        signupUrl: 'https://secure.premierinn.com/en/mypremierinn/register.action',
        forgotPasswordLink: 'https://secure.premierinn.com/en/mypremierinn/forgottenPassword.action',
      },
      business: {
        signupUrl: 'https://business.premierinn.com/content/cbt/en/login.html',
        forgotPasswordLink: 'https://business.premierinn.com/content/cbt/en/profile/reset-password.html',
      },
      businessLoginRedirectPath: '',
      accountLinks: [
        {
          title: 'Bookings',
          url: 'https://secure.premierinn.com/en/mypremierinn/pastBookings.action',
          icon: 'bookings',
        },
        {
          title: 'Profile',
          url: 'https://secure.premierinn.com/en/mypremierinn/personalDetails.action',
          icon: 'settings',
        },
      ],
      microserviceUri: 'https://api-uat.whitbread.co.uk',
      forgottenPasswordPath: '/auth/hotels/forgot-password',
      forgottenPasswordRequestUrl: 'https://secure.premierinn.com.staging.nativ-systems.com/en/mypremierinn/resetPassword.action?business={isBusinessBrand}&token=',
      rememberPreferredBrand: {
        daysTillExpiry: 7,
      },
      rememberMeEnabled: true,
      loggedInState: {
        userButtonBottomLineLength: 26,
      },
    },
    features: {
      hotelSearch: true,
      bookingSearch: true,
      languageSelector: true,
      authentication: true,
      subNav: true,
      analytics: false,
      dashboardRedirectEnabled: true,
    },
    search: {
      route: true,
      searchPath: 'https://www.premierinn.com/gb/en/search.html',
    },
    bookingSearch: {
      bookingSearchPath: 'https://secure.premierinn.com.de-qa.nativ-systems.com/en/processSearchForBooking.action',
      dashboardRedirect: {
        url: 'https://pi-bookings.netlify.com/en',
        bookingReference: 'bookingReference',
        cookie: {
          name: 'pi.single-booking',
          minutesTillExpiry: 30,
        },
      },
    },
    businessHours: {
      start: 9,
      end: 17,
    },
    experiments: {
      flexOnlyRate: false,
      snowDropRandom: false,
      snowDropSortBy: false,
      snowDropSortByKey: 'suggestion',
      dateless: {
        message: false, // Sets whether the ”Please select your date” message is present
        calendar: false, // Sets whether the calender is open and if button should display
        overlay: false, // Sets the opaque background over the page on SRP only
      },
    },
  },
  content: {
    global: {
      adult: 'adult',
      adults: 'adults',
      child: 'child',
      children: 'children',
      nights: 'nights',
      night: 'night',
      room: 'room',
      rooms: 'rooms',
      today: 'Today',
      tomorrow: 'Tomorrow',
      maxRooms: 4,
      offers: [
        {
          maxRooms: 2,
          cellCode: 'SHA02',
          page: 'shareholder-offer',
          numberOfNights: 9,
        },
        {
          maxRooms: 4,
          cellCode: 'COSTA',
          page: 'costa-offer',
          numberOfNights: 9,
        },
        {
          maxRooms: 4,
          cellCode: 'EMP01',
          page: 'employee-offer',
          numberOfNights: 9,
        },
      ],
      family: 'Family',
      double: 'Double',
      single: 'Single',
      accessible: 'Accessible',
      twin: 'Twin',
      addRoom: 'Add another room',
      done: 'Done',
      roomLabel: 'Room',
      brand: {
        pi: 'Premier Inn',
        hub: 'hub by Premier Inn',
        zip: 'Zip by Premier Inn',
        piLogo: '//www.premierinn.com/content/dam/pi/websites/desktop/icons/brand/pi-icon-disc.svg',
        hubLogo: '//www.premierinn.com/content/dam/pi/websites/desktop/icons/brand/pi-icon-disc-hub.svg',
        zipLogo: '//www.premierinn.com/content/dam/pi/websites/desktop/icons/brand/pi-icon-disc-zip.svg',
      },
    },
    menu: {
      mobileMenuButton: 'Menu',
      languageButton: 'English',
      logIn: 'Log in',
      bookHotel: 'Book a hotel',
      findBooking: 'Find bookings',
    },
    hero: {
      heading: 'Book a hotel',
      subHeading: 'Our high-quality hotel rooms. Ideal for families , business and leisure.',
      footnoteLocation: 'Southwold, Suffolk',
      footnoteHotel: 'Mearest Premier Inn, Lowestoft',
      footnotePosRight: false,
      image: 'https://www.premierinn.com/content/dam/pi/websites/desktop/homepage/homepage-tests/Desktop-3200_x_1200__kids_friendly.jpg.pagespeed.ce.31GNLp9KuA.jpg',
    },
    navLinks: [{
      title: 'Find Booking',
      url: 'https://secure.premierinn.com/en/searchForBooking.action',
    }],
    countries: [{
      language: 'English',
      url: 'http://premierinn.com',
      code: 'gb',
      flagUrl: '//www.premierinn.com/content/dam/global/flags/United-Kingdom.png',
    },
    {
      language: 'Deutsch',
      url: 'http://premierinn.de',
      code: 'de',
      flagUrl: '//www.premierinn.com/content/dam/global/flags/Germany.png',
    },
    ],
    form: {
      hotelsLabel: 'Hotels',
      where: 'Enter place, postcode or hotel',
      search: 'Search',
      groupBooking: 'Group booking',
      bookingReference: 'Booking reference',
      bookingSurname: 'Surname',
      bookingInvalid: 'Some of these details are missing or invalid. Please provide correct details',
      bookingTypeInvalid: 'To search for Business Booker stays, please visit our Business Booker portal',
      invalidLocation: 'Please enter a location or a hotel',
      snowdropError: 'Oh dear, something went wrong when we tried to load the suggestions.',
      snowdropErrorRetry: 'Retry',
      snowdropErrorLinkConnector: 'or',
      snowdropErrorHotelDirectory: 'Load hotel directory',
      snowdropErrorUrl: '//www.premierinn.com/gb/en/hotels.html',
      invalidFutureDate: 'Unable to book over a year in advance',
      invalidPastDate: 'Your selected date is in the past',
      invalidDate: 'Please enter a valid date',
      invalidNights: 'Enter a valid number of nights',
      invalidRooms: 'Please enter a valid room composition',
      invalidReference: 'invalidReference Copy required - 2 characters / special character',
      invalidSurname: 'invalidSurname Copy required - 2 characters / special character',
      change: 'Change search',
      summary: 'You searched for',
      checkout: 'Check out:',
      removeRoom: 'Remove Room',
      room: 'Room',
      cot: 'Cot',
      numberOfNights: 9,
      datePicker: {
        previousMonth: 'Previous Month',
        nextMonth: 'Next Month',
        months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        pickADate: 'Please select a date',
        unknownDates: 'I don\'t know my dates',
      },
    },
    results: {
      notifications: {
        groupBookingMessage: 'If you’d like to book five rooms or more, please call us and we’ll be happy to help.',
        noResults: 'Sorry, we couldn’t find any hotels with available rooms. Try changing your search area.',
      },
    },
    header: {
      image: '//www.premierinn.com/content/dam/pi/websites/desktop/icons/brand/pi-logo-white.svg',
    },
    privacyPolicy: {
      text: 'Privacy Policy',
      link: '/gb/en/terms/privacy-policy.html',
    },
    authentication: {
      loginButton: 'Log in',
      logoutButton: 'Log out',
      accountDescription: 'Your account',
      login: {
        leisure: {
          tab: 'My Premier Inn',
          formLabel: 'Log into your Premier Inn account',
          signupButton: 'Sign up to My Premier Inn',
          loginButton: 'Log in',
          emailPlaceholder: 'Email address',
        },
        business: {
          tab: 'Business Booker',
          formLabel: 'Log into Business Booker',
          loginButton: 'Log in to Business Booker',
          signupButton: 'Sign up to Business Booker',
          emailPlaceholder: 'Business email address',
        },
        invalidEmail: 'Please enter a valid e-mail address.',
        badCredentialsError: 'Your email address or password is incorrect.',
        genericError: 'Looks like something went wrong, please try again later.',
        forgotPassword: 'Forgotten password?',
        passwordPlaceholder: 'Password',
        rememberMeLabel: 'Remember me',
        sessionExpired: 'Your session expired, please login again.',
      },
      forgottenPassword: {
        leisure: {
          formTitle: 'Reset your password',
          formLabel: 'We will send you an email with instructions to reset your password',
          submitButton: 'Submit',
          emailPlaceholder: 'Email address',
        },
        business: {
          formTitle: 'Reset your business password',
          formLabel: 'We will send you an email with instructions to reset your password',
          submitButton: 'Submit',
          emailPlaceholder: 'Email address',
        },
        emailSentHeader: 'Email sent',
        emailSentMessage: 'We\'ve sent you an email with instructions to reset your password',
        cancel: 'Cancel',
        genericError: 'Looks like something went wrong, please try again later.',
        notRegisteredError: 'We don’t recognise this email address.',
      },
    },
    subNav: [
      // tslint:disable:max-line-length
      { title: 'In our hotels', navOptions: [{ title: 'Accomodation', url: '/gb/en/in-our-hotel/accomodation' }, { title: 'Our rooms', url: '/gb/en/in-our-hotel/our-rooms' }, { title: 'Free Wi-Fi', url: '/gb/en/in-our-hotel/free-wifi' }, { title: 'Bike-Friendly', url: '/gb/en/in-our-hotel/bike-friendly' }, { title: 'Family', url: '/gb/en/in-our-hotel/family' }] },
      { title: 'Business', navOptions: [{ title: 'Business Account', url: '/gb/en/in-our-hotel/business-account' }, { title: 'Business Booker', url: '/gb/en/in-our-hotel/business-booker' }, { title: 'Premier Inn Meetings', url: '/gb/en/in-our-hotel/premier-inn-meetings' }, { title: 'Business Guest Information', url: '/gb/en/in-our-hotel/business-guest-information' }] },
      { title: 'Short Breaks', navOptions: [{ title: 'Plan your trip', url: '/gb/en/in-our-hotel/plan-your-trip' }, { title: 'All short breaks', url: '/gb/en/in-our-hotel/all-short-breaks' }, { title: 'Family breaks', url: '/gb/en/in-our-hotel/family-breaks' }, { title: 'City Breaks', url: '/gb/en/in-our-hotel/city-breaks' }] },
      { title: 'Hotel Locations', navOptions: [{ title: 'Airport hotels', url: '/gb/en/in-our-hotel/airport-hotels' }, { title: 'Hotels close to universities', url: '/gb/en/in-our-hotel/hotels-close-to-universities' }, { title: 'Hotels near entertainment venues', url: '/gb/en/in-our-hotel/hotels-near-entertainment-venues' }, { title: 'New hotels', url: '/gb/en/in-our-hotel/new-hotels' }] },
    ],
  },
};
